### PR TITLE
executor.go: improve stdio reliability even more

### PR DESCRIPTION
**Pull request by erikh**
This uses ioutil.ReadAll to drain the buffers which seems to be more reliable, and a retry mechanism for the reading just in case io.Copy breaks (Which it appears to occasionally).

### CODE REVIEW

**Comment by erikh** [comment]
PTAL @mapuri @unclejack

**Comment by erikh** [comment]
still broken, back to the drawing board

**Comment by mapuri** [comment]
@erikh 

not sure if this helps in anyway but thought will share just in case you are hitting something related. For using `Cmd.StdoutPipe()`, the `Cmd.Wait()` can only be called after reader has completed reading everything. So it kind of forces reading all output exactly between calls to `Cmd.Start()` and `Cmd.Wait()`.

https://golang.org/pkg/os/exec/#Cmd.StdoutPipe

I had struggled with this for a bit while writing ansible-runner (https://github.com/contiv/cluster/blob/master/management/src/ansible/ansible.go#L40). 

The solution that I came up was to set the `Cmd.Stdout` and `Cmd.Stderr` of the cmd to the one provided by the caller. This removes the need for `Cmd.Wait()` being called in above order and let's caller setup it's own pipe on top of the writer it passes to the ansible-runner in my case.

**Comment by erikh** [comment]
I see, that explains some things. I'm going to leave this alone because 
it is very hard to trigger.

**Pull request closed without merging**
